### PR TITLE
Add some type checking tests

### PR DESCRIPTION
**Pull request by DarkDrek**
Tests for type checking errors for #7
Handles some (not all) cases from #20 
I want to get some feedback if this style of checking is desired.

The new test module type_check handles the successful cases and its sub-module error handles the erroneous ones.
This can be merged if the structure is ok for a test foundation.

List of handled cases:
- `true` and `false` must be `Bool`s.
- numbers must be `Int`.
- Check that binary operations are rejected if the terms doesn't have the same type.
- Check that binary operations are rejected if the terms doesn't have the same type.
- Check that arithmetic operations have type `Int` and only work with integers.
- Check that boolean operations have type `Bool` and only work with booleans.
- Check that integer comparison operations have type `Bool`  and only work with integers.
- Check that equal and not equal have type `Bool` for every base type.
- Check that arithmetic operations have type `Int` and only work with integers.
- Check that boolean operations have type `Bool` and only work with booleans.
- Check that `if x do y else z end` has type `T` if `y` and `z` have type `T` and `x` has type `Bool`.
- Check that `if x do y else z end` is rejected if `y` and `z` have different types.
- Check that `if x do y else z end` is rejected if `x` is not a boolean.

### CODE REVIEW

**Comment by pvdrz** [comment]
This looks great, do yo want to add a test for each rule we have in this PR? or do you just want to set some foundations so we can write them later?

**Comment by DarkDrek** [comment]
I still want add tests where I can write the cases myself based on my current knowledge about the language (~3 hours :smile:)

**Comment by pvdrz** [comment]
Heh :P I'll add some notes to https://github.com/christianpoveda/pijama/issues/7

Edit: I ended up opening a new issue :P

**Comment by DarkDrek** [comment]
So I implemented some more tests. Now also for successful type checked programs. Can be merged when no changes are requested. Added a summary of added test in the top comment (without guarantee of completeness)

**Review by pvdrz — APPROVED** [review]
Thanks for the help with the tests. I've updated https://github.com/christianpoveda/pijama/issues/20 to include most of the tests you added here.

**Pull request merged**
