### PR TITLE
[WIP/Idea] Implement inbuilt function print

### LINKED ISSUE #44: Add a print built-in function
It would be nice to have a function able to print values available. However, there are several things that need to be sorted out first:
- [x] What should be the name of the function?  (`print` was our choice)

  `print` and `puts` are the first two options that come to mind.
- [x] What should be the type of such function?  (`T -> Unit` was our choice)

    I think it is too soon to start worrying about the fact that printing is a fallible operation (so no effects for now). The two options I can think of are:
   -  `T -> Unit`: The function consumes the term to be printed.
   -  `T -> T`: The function returns the term after printing it.
   

- [ ] What can be printed? 
    
    The argument of the function should be evaluated to print it, but the evaluation could end in a function or any other term that is not a literal. There is no way to recover the AST representation of terms so we'd have to show the LIR of the term.

Update: Even though we still have to decide what can be printed. We can start working towards an implementation of this once https://github.com/christianpoveda/pijama/issues/54, https://github.com/christianpoveda/pijama/issues/55 and https://github.com/christianpoveda/pijama/issues/56 are resolved.

The steps we need to take are:
- [ ] add a new `Print` variant to `ast::Primitive`.
- [ ] add the `stdout` stream to `Machine`.
- [ ] change the `Machine::step_primitive_app` to print stuff using the stream.
- [ ] update `ty::ty_check` to inspect terms with the pattern
    ```rust
    Term::App(Term::PrimitiveFn(Primitive::Print), t1)
    ```
    and assign them the type `Unit`.
- [ ] Fix parsing by adding a new `parser::primitive` module to produce `Primitive` elements (more instructions soon).

### PR DESCRIPTION
**Pull request by DarkDrek**
Add environment to lir::evaluate

This is just a quick & somewhat dirty approach of implementing #44 
@christianpoveda Was my way of implementing it correct or is there a easier way. Some parts are just copy&paste.
I added a `LangEnv` type for `stdout` so I can overwrite it the tests but I'm open to discuss different approaches to solve the underlying problem of global variables that are accessed during evaluation.

### CODE REVIEW

**Comment by pvdrz** [comment]
Oh wow, I didn't expect this PR! Thanks! I will be AFK today so I'll drop my raw, unedited comments here:

So, I think that stateful evaluation is an step in the right direction. We'll need that if we want to have a decent language in terms of performance.

However, I think it will be more future proof to write a `Machine` struct (probably inside a new top-level module called `eval` or `machine` idk) and let the evaluation environment be a field of that new struct.

I'm asking for this because eventually we will have more state, some of it will be to interact with the OS like `print` but also the actual runtime of the language, like the heap, the stack  and even a GC instead of relying on Rust for memory management. And putting all that as arguments of a function won't take us very far. 

 The idea would be to (eventually and in another PR) move all the logic of `lir/eval` to this new machine.

My second comment goes about the IR of these new built-in functions. I think it would me more scalable to keep them contained in a single type. Something like

```rust
enum BuiltIn {
    Print
}
```
And add a new variant inside `lir::Term`:

```rust
enum Term {
    ...
    BuiltIn(Builtin),
}
```

Such that the LIR of a print call looks like `Term::App(box Builtin(Builtin::Print), box t1)`.

There are some questions that we haven't answered yet, like what happens if someone writes: 

```pijama
print = fn(x: Int) do x end
print(10)
```
Should we forbid `print` as a name for variables and parse it always as a `BuiltIn`? Is not like is hard to do but we have to take that decision.

Thanks for this PR, I'd never imagine that this project will gain this level of traction so quickly, I hope these comments I wrote above aren't discouraging.

**Comment by DarkDrek** [comment]
> Thanks for this PR, I'd never imagine that this project will gain this level of traction so quickly, I hope these comments I wrote above aren't discouraging.

No problem the comments are great I will try experimenting with it a bit more.

PS: Have a nice AFK time 😄

**Comment by DarkDrek** [comment]
Tried to follow your second comment. The code is far from perfect. It is not clear who manages the global knowledge about the builtins during type checking and lowering operations. But it works (tests pass). I added a test for the redefined case to see the result in the test case.

Feel free to comment 😃.

**Comment by seanchen1991** [comment]
Makes sense to forbid `print` from being a variable name 👍

**Comment by pvdrz** [comment]
I like the new `BuiltInFn` type. However I think we can move its creation all the way back to parsing. Can you move it to the `ast` module and add a new module `parser::built_in_fn` to parse them? I think you need to get into `parser::name` and add `"print"` to `KEYWORDS` to avoid parsing ambiguities.

Doing things that way forbids programs like `print = 5` because the parser will say that `print` is a `BuiltInFn` instead of a `Name`

**Comment by DarkDrek** [comment]
Another batch of changes. I added the `either` crate to differentiate between a builtin fn call and a normal one.

Also I added a first version of a `Machine` struct. I'm not sure if we still need the step_in_place method now. The only benefit I see is that we reuse a created `Box` but maybe the overhead of un/packing is higher than just creating a new `Box`?

**Comment by pvdrz** [comment]
Hmm your changes made me think that we might need to do certain fixes to allow more than names in calls. In other words if we are able to parse stuff like:
```
(fn(x: Int) do x end)(1)
```
Then we can change `Node::Call(Name, Block)` to `Node::Call(Node, Block)` and then add primitive functions as simple `Node`s. Which would simplify a lot of what needs to be done in the other IRs.

I think maybe it is too early to implement this :/. However I'd say we can work iteratively in this direction. If you want I can open issues for the problems that are making this difficult.

**Comment by DarkDrek** [comment]
Sure open a issue for the encountered problems. And implement this nicer when we have a more generic representation of function calls.

PS: Or did I misunderstood you and you want to merge this without your mentioned changes and then in a later PR fix the representation off function calls?

**Comment by DarkDrek** [comment]
Moved the non `pub` evaluation functions of `Machine` to the `eval` submodule.

Changed `Machine` and `LangEnv` to be generic over `Write` instad of using `&dyn Trait`. It makes creating a `Machine` a bit easier because we don't have to worry about lifetimes since it can take ownership of its members. But if we add more members with different generics the `Machine` signatur may become harder to read.

**Comment by pvdrz** [comment]
> Sure open a issue for the encountered problems. And implement this nicer when we have a more generic representation of function calls.

Yes we can come back to this when we have all the missing parts. I think that we could do this an small project goal and tag the issues we need to get here.

**Comment by pvdrz** [comment]
I've created https://github.com/christianpoveda/pijama/issues/54 and https://github.com/christianpoveda/pijama/issues/55 to address the improvements we need to do before getting here.

**Comment by DarkDrek** [comment]
Made this a draft because it doesn't make sense to merge it in its current form and if we can implement it it is probably better to to it in another PR. But we should keep it open to preserve the discussion until the underlying issue is implemented.

**Comment by pvdrz** [comment]
Yes I feel we're missing a space to have this sort of quick discussions. But let's keep this one to recycle the parts you've already changed.

**Pull request closed without merging**
