### PR TITLE
Remove nightly features

### PR DESCRIPTION
**Pull request by DarkDrek**
An attempt at #60

There is still some room for improvement but at least it compiles now. I had to juggle with `*`, `&` and so on to get it to compile 🤯 

PS: I changed travis to compile on all channels to test this.

### CODE REVIEW

**Comment by DarkDrek** [comment]
ouch 🤕 
```
arithmetic              time:   [102.37 us 102.81 us 103.38 us]
                        change: [+321.99% +326.51% +330.90%] (p = 0.00 < 0.05)
logic                   time:   [219.73 us 221.42 us 223.66 us]
                        change: [+447.03% +450.84% +455.72%] (p = 0.00 < 0.05)
factorial               time:   [245.19 us 253.34 us 262.58 us]
                        change: [+264.80% +269.78% +275.32%] (p = 0.00 < 0.05)f
factorial_tail          time:   [377.31 us 388.91 us 397.96 us]
                        change: [+147.72% +156.96% +165.97%] (p = 0.00 < 0.05)
fibonacci               time:   [1.4564 ms 1.4658 ms 1.4762 ms]
                        change: [+74.127% +75.229% +76.499%] (p = 0.00 < 0.05)
fibonacci_tail          time:   [269.60 us 271.63 us 274.70 us]
                        change: [+144.92% +147.12% +149.05%] (p = 0.00 < 0.05)
gcd                     time:   [1.9357 ms 1.9447 ms 1.9569 ms]
                        change: [+153.71% +155.84% +157.87%] (p = 0.00 < 0.05)
ackermann               time:   [1.0583 ms 1.0660 ms 1.0757 ms]
                        change: [+41.252% +42.365% +43.741%] (p = 0.00 < 0.05)
calling                 time:   [360.12 us 377.76 us 399.43 us]
                        change: [+174.62% +181.54% +189.21%] (p = 0.00 < 0.05)
complex_calling         time:   [383.35 us 386.69 us 390.35 us]
                        change: [+165.19% +167.59% +169.86%] (p = 0.00 < 0.05)
fancy_max               time:   [10.122 us 10.192 us 10.286 us]
                        change: [+86.139% +95.706% +105.40%] (p = 0.00 < 0.05)
step                    time:   [4.9155 us 4.9423 us 4.9807 us]
                        change: [+69.055% +75.369% +82.332%] (p = 0.00 < 0.05)
```

**Comment by DarkDrek** [comment]
I will try rewriting (again) it to use `Box<Term>` everywhere or can you @christianpoveda see any obvious performance pitfalls?

**Comment by DarkDrek** [comment]
Now it's a lot better

PS: now it can be reviewed and maybe be merged.

```
arithmetic              time:   [21.998 us 22.280 us 22.593 us]
                        change: [-7.6923% -5.2814% -3.1165%] (p = 0.00 < 0.05)
logic                   time:   [37.447 us 37.576 us 37.734 us]
                        change: [-5.7296% -5.2537% -4.8126%] (p = 0.00 < 0.05)
factorial               time:   [73.788 us 74.226 us 74.728 us]
                        change: [+20.319% +21.106% +21.989%] (p = 0.00 < 0.05)
factorial_tail          time:   [144.32 us 144.91 us 145.73 us]
                        change: [+7.6753% +8.5378% +9.3545%] (p = 0.00 < 0.05)
fibonacci               time:   [580.01 us 584.15 us 589.39 us]
                        change: [+0.4958% +1.4600% +2.3722%] (p = 0.00 < 0.05)
fibonacci_tail          time:   [117.32 us 117.92 us 118.97 us]
                        change: [+2.8738% +3.7311% +4.7212%] (p = 0.00 < 0.05)
gcd                     time:   [790.96 us 795.26 us 801.09 us]
                        change: [-27.844% -27.225% -26.567%] (p = 0.00 < 0.05)
ackermann               time:   [462.81 us 470.78 us 481.07 us]
                        change: [+4.2051% +6.4999% +9.0708%] (p = 0.00 < 0.05)
calling                 time:   [129.89 us 130.65 us 131.59 us]
                        change: [+0.7351% +1.6601% +2.8169%] (p = 0.00 < 0.05)
complex_calling         time:   [144.75 us 145.93 us 147.41 us]
                        change: [-1.3098% -0.4648% +0.5070%] (p = 0.33 > 0.05)
fancy_max               time:   [3.5541 us 3.5925 us 3.6482 us]
                        change: [+0.3051% +1.3901% +2.4574%] (p = 0.01 < 0.05)
step                    time:   [2.8314 us 2.9380 us 3.0226 us]
                        change: [+51.835% +58.966% +65.893%] (p = 0.00 < 0.05)
```

**Comment by pvdrz** [comment]
> I will try rewriting (again) it to use `Box<Term>` everywhere or can you @christianpoveda see any obvious performance pitfalls?

I would've done the same as you. I cannot see any pitfalls there. It is possible that the current nightly has certain optimizations that are missing in stable (maybe?). What happens if you run the benchmarks in nightly with the current changes?

**Comment by pvdrz** [comment]
Ohh I just saw your new comment. Those look better but I'm amazed by how such change could affect things so drastically. Can you run `cargo clippy` to see if we are doing some unnecessary boxing according to the lints? Otherwise we are good to go.

**Comment by DarkDrek** [comment]
> Ohh I just saw your new comment. Those look better but I'm amazed by how such change could affect things so drastically. Can you run `cargo clippy` to see if we are doing some unnecessary boxing according to the lints? Otherwise we are good to go.

No complaints from clippy about that there was one place in `step_beta_reduction` where a `Box<Term>` argument was unnecessary but I already did fix that.

**Review by pvdrz — APPROVED** [review]
Then let's merge this :)

**Pull request merged**
